### ISSUE TITLE
Slow parameter transfer via USB since 2.0.11

### ISSUE THREAD

**Issue by hsteinhaus** [diydrones/apm_planner#398]
After upgrading from 2.0.10 to 2.0.11 the parameter transfer via USB connection is painfully slow. With 2.0.10, the transfer of 414 parameters took less than a second, now is about 5-10 seconds (varying). The new behaviour is somewhat similar to the transfer via 3DR radio now: fast transfer of the first 100 parms, than very sluggish transfer of the rest.

Used OS: Fedora 19/x86_64, compiled from sources.
FC: Pixhawk, current master

**Comment by hsteinhaus** [comment]
Update for version (5f3e9179-2.0.16-rc1-37-g5f3e917): I am pretty sure now that even the radio link is affected by the same problem. The first 150 params are transfered rather fast, then there is a significant drop in speed (all radios are within a few meters).

**Comment by malcom2073** [comment]
Are you compiling with debug symbols, or without?

**Comment by hsteinhaus** [comment]
I am using the release build, so I guess without.

**Comment by billbonney** [comment]
Have reproduced the issue, but only on an older 32Bit Linux machine. I have a fix by reducing the amount of logging, the slowdown happens much later now, but it still slows down. I'll need to investigate more why this is.

**Comment by hsteinhaus** [comment]
My current machine is Dell 6430 ATG (medium-sized laptop, Core-i5, SSD, 8G RAM), running Centos 7.0 64 bit. At the time I started this issue I was still using a much faster desktop machine (4 core, 16G RAM, even faster SSD). Let me know if I can help with some testing.

**Comment by hsteinhaus** [comment]
BTW, there seems to be no real load during the parameter transfer, neither CPU nor IO. So I really guess this problem is related to some locking stuff...

**Comment by billbonney** [comment]
I've pushed some changes with this commit, but I need to look a bit deeper to really understand why the slow down 8f464d4

**Comment by hsteinhaus** [comment]
I have tried the changes. I have seen one very fast parameter load (too fast?), lots of loads at the usual slow speed, some failed connects and a few crashes (segfault).

**Comment by malcom2073** [comment]
Since you're compiling with source, can you get a stacktrace with gdb when it crashes? I'll get a Centos install going and see if I can reproduce it, I don't see the crash on Fedora, though I do see the slowdown.

**Comment by hsteinhaus** [comment]
Yes, will try to do that tomorrow.

**Comment by hsteinhaus** [comment]
After a few hundred dis/reconnects I regret to report that the crash only happens with the release build. When using debug executable or running in gdb, it has never ever crashed. +1 for race condition stuff...

**Comment by hsteinhaus** [comment]
finally catch a core file using the releese build. Obviously it has no debug symbols, but may be it contains a hint:

#0  0x00007f153a8c39ed in QV8Engine::toVariant(QV4::ValueRef, int) () from /opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Qml.so.5
#1  0x00007f153a841a0a in QQmlPropertyPrivate::writeBinding(QObject*, QQmlPropertyData const&, QQmlContextData*, QQmlJavaScriptExpression*, QV4::ValueRef, bool, QFlags<QQmlPropertyPrivate::WriteFlag>) () from /opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Qml.so.5
#2  0x00007f153a8afca7 in QQmlBinding::update(QFlags<QQmlPropertyPrivate::WriteFlag>) () from /opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Qml.so.5
#3  0x00007f153a83bdb7 in QQmlPropertyPrivate::setBinding(QObject*, int, int, QQmlAbstractBinding*, QFlags<QQmlPropertyPrivate::WriteFlag>) ()
   from /opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Qml.so.5
#4  0x00007f153a805f43 in QV4::QObjectWrapper::setProperty(QObject*, QV4::ExecutionContext*, QQmlPropertyData*, QV4::ValueRef) ()
   from /opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Qml.so.5
#5  0x00007f153a815517 in QV4::Runtime::setQmlQObjectProperty(QV4::ExecutionContext*, QV4::ValueRef, int, QV4::ValueRef) ()
   from /opt/Qt5.3.2/5.3/gcc_64/lib/libQt5Qml.so.5
#6  0x00007f153d6bd2c9 in ?? ()
#7  0x00000000033ebf30 in ?? ()
#8  0x0000800000000000 in ?? ()
#9  0x00007f152000f210 in ?? ()
#10 0x0003000000000002 in ?? ()
#11 0x00007f152009c000 in ?? ()
#12 0x00007f151094d050 in ?? ()
#13 0x00007fff970335d0 in ?? ()
#14 0x0000000000000000 in ?? ()

**Comment by billbonney** [comment]
Try a build with Qt5.4 as they have done some changes to how QSerialPort works in that build (which actually crashes OSX, but might fix your issue)

**Comment by billbonney** [comment]
PS: You can have debug symbols in release builds. A release build just has the compiler optimizer turned on which makes stepping through code harder for debugging

**Comment by hsteinhaus** [comment]
I think I found the reason for the varying speed of the parameter transfer: APM Planner seems to start reading waypoints from the drone at a certain point in time (when paramter transfer is about 70% complete). When downloading 80 waypoints, this nearly inhibits the parameter transfer for about 20 seconds. Thereafter, the parameter transfer resumes at normal speed.

Maybe some form of serialization (parameters first, mission later, or vice versa) would improve usability here?
