### ISSUE TITLE
3dr updating firmware error using sik_uploader.py

### ISSUE THREAD

**Issue by xros** [diydrones/apm_planner#791]
I have this error when flashing 3DR radio firmware on linux using APM planner 2.

> Flashing with firmware
> ./sik_uploader/firmware/1.9/radio~hm_trp.ihx
> ..............................uploading to port /dev/ttyUSB0
> Connecting to /dev/ttyUSB0
> Trying autosync
> ...........+++
> +++...........Traceback (most recent call last):
>   File "./sik_uploader/sik_uploader.py", line 278, in <module>
>     if not up.check():
>   File "./sik_uploader/sik_uploader.py", line 237, in check
>     self.autosync()
>   File "./sik_uploader/sik_uploader.py", line 207, in autosync
>     except fdpexpect.TIMEOUT:
> AttributeError: 'module' object has no attribute 'TIMEOUT'

And I checked out the codes:
Here: https://github.com/diydrones/apm_planner/blob/master/sik_uploader/sik_uploader.py#L207
It does not have the property in module _fdpexpect_.

So I think there should be a fix.

**Comment by xros** [comment]
and the correct line should be 
> pexpect.TIMEOUT

in line 207

**Comment by xros** [comment]
When I was building the apm for linux(ubuntu14.04) i found the libfreenect settings in this project is too old. Some functions are renamed or gone.

**Comment by billbonney** [comment]
I think you are missing the python-pexpect module for python

`sudo apt-get install python-pexpect' will fix it.

**Comment by xros** [comment]
I have fixed the bug and pulled a request. 

*https://github.com/diydrones/apm_planner/pull/792*

Please check it out if having time.
